### ISSUE TITLE
No Display - Acer ChromeBase CA24I2

### ISSUE THREAD

**Issue by wamsparky** [MrChromebox/scripts#245] opened 2022-12-29 05:08 UTC
So i proceed to the flash the coreboot_tiano-karma-mrchromebox_20221129.rom through NeoProgrammer tool, but after completion and attempt to power on the device there is no display. Only led light to show power is present. Can someone guide me if i did something wrong.

I have Acer ChromeBase CA24I2-5T model which i believe should be the KARMA model

**Comment by MrChromebox** [comment] 2022-12-30 16:31
not aware of any issues with KARMA, but probably only been flashed a handful of times thus far. I can give you another build with a different display init method and see if that helps

**Comment by wamsparky** [comment] 2022-12-30 17:12
Yes please do, I would really appreciate it as I had this enterprise locked and tried KARMA flash. I reflashed the backups but nothing. Should power be going to the board while flashing or no, or can that affect the chip.

**Comment by MrChromebox** [comment] 2022-12-30 20:09
if the stock backup isn't working, sounds like an issue with the flashing. All power should be disconnected from the board when flashing

**Comment by wamsparky** [comment] 2022-12-30 20:17
So what suggestions would you recommend, when I first flashed it, it did come up but with the same settings. No changes. So I was wondering if I was connecting to the wrong IC, but I backed up both IC but wasn't flashable due to incorrect buffer amount so I knew it was the next IC, my model is CA24I2-5T I am wondering if it's the same Karma rom

**Comment by MrChromebox** [comment] 2022-12-31 19:39
a KARMA is a KARMA is a KARMA.

If the stock backup you made isn't working, the issue is with your flashing setup. All power should be disconnected when connecting the chip clip.

**Comment by wamsparky** [comment] 2022-12-31 19:55
So meaning the program might me reading the chip but not connected properly ? As I attempted the flash again but now led light is flashing blue

**Comment by MrChromebox** [comment] 2022-12-31 21:32
as in, you are not reading nor writing the chip properly. Your backup is almost certainly not valid. See if this one works for you:

[coreboot-Google_Karma.11343.22.0.zip](https://github.com/MrChromebox/scripts/files/10327990/coreboot-Google_Karma.11343.22.0.zip)

**Comment by wamsparky** [comment] 2022-12-31 21:35
Will test and get back to you but I find it strange as it successfully save the backup. I will use the neoprogrammer to flash

**Comment by MrChromebox** [comment] 2022-12-31 21:36
just because it read and saved data doesn't mean that data matches what is on the chip

**Comment by wamsparky** [comment] 2022-12-31 21:41
Understood let me try this flash.

**Comment by wamsparky** [comment] 2022-12-31 21:47
> just because it read and saved data doesn't mean that data matches what is on the chip

odd that this data was pulled from the chip. I will erase the chip and flash what you gave

**Comment by wamsparky** [comment] 2022-12-31 22:36
I erase the IC flashed with the provided rom and it still flashes a blue light on power led no when i power on

**Comment by MrChromebox** [comment] 2022-12-31 23:01
did you erase the other chip (EC firmware) by chance?

**Comment by wamsparky** [comment] 2022-12-31 23:02
No i didnt but i did a backup of that IC as well but i couldnt flash that IC as image/buffer didnt match

**Comment by MrChromebox** [comment] 2022-12-31 23:05
please zip/upload the backups of the two SOIC-8 chips that you read

**Comment by wamsparky** [comment] 2022-12-31 23:06
they are .bin files

**Comment by wamsparky** [comment] 2022-12-31 23:09
[Chromebase Dump.zip](https://github.com/MrChromebox/scripts/files/10328100/Chromebase.Dump.zip)

Please see here

**Comment by wamsparky** [comment] 2022-12-31 23:10
thanks also for the support

**Comment by MrChromebox** [comment] 2022-12-31 23:12
those look sane. Are you sure you don't have the display cable disconnected?

**Comment by wamsparky** [comment] 2022-12-31 23:25
display cable is connected to the board i removed and reseated a few times. should i remove all connections when flashing the board and CMOS battery ?

**Comment by MrChromebox** [comment] 2022-12-31 23:27
just external power. CMOS shouldn't matter but ok to remove

**Comment by MrChromebox** [comment] 2022-12-31 23:33
here is a karma UEFI test build with alternate display init method

[coreboot_tiano-karma-mrchromebox_20221231.zip](https://github.com/MrChromebox/scripts/files/10328113/coreboot_tiano-karma-mrchromebox_20221231.zip)

**Comment by wamsparky** [comment] 2022-12-31 23:45
i am still at a lost i am wondering what i messed up. i ever tried different RAM chips and still just flashing blue light. do you know where i could source a board.


.......I will test this one as this model Chromebase is 2021 model. was this first flash legacy flash ?

**Comment by wamsparky** [comment] 2022-12-31 23:51
Ch341a Programmer V2.2.0.10 vs NeoProgrammer V2.2.0.10 is there a difference

**Comment by wamsparky** [comment] 2023-01-01 01:12
still no luck i am going to purchase another flashing board i am wondering if this one is faulty

**Comment by MrChromebox** [comment] 2023-01-01 16:23
I have no idea what NeoPogrammer is, is it a software app? It is recommended to use flashrom under Linux

**Comment by wamsparky** [comment] 2023-01-01 17:33
I was going off a video I saw on YouTube. Do you have a link for flashrom ? As it was those programs I used to creat thos backups

**Comment by MrChromebox** [comment] 2023-01-01 18:38
see https://wiki.mrchromebox.tech/Unbricking

**Comment by wamsparky** [comment] 2023-01-01 18:48
> see https://wiki.mrchromebox.tech/Unbricking

The issue is i am using a windows PC, i guess the 2 software I quoted are for windows environment

**Comment by wamsparky** [comment] 2023-01-02 23:53
question should i be using 25SPI BIOS or 24I2C EEPROM

**Comment by MrChromebox** [comment] 2023-01-03 00:06
25SPI

**Comment by wamsparky** [comment] 2023-01-03 00:07
ok just making sure, i am the new one

**Comment by MrChromebox** [comment] 2023-02-04 20:15
not a script issue; closing

**Closed by MrChromebox** 2023-02-04 20:15 UTC
