### ISSUE TITLE
HP Chromebook 11A G6 EE (BARLA) - CPU 50%

### ISSUE THREAD

**Issue by BliNeR-KeY** [MrChromebox/scripts#350] opened 2024-01-19 09:31 UTC
Hello i have installed windows 11- Lite in my HP Chromebook 11A G6 EE (BARLA) 

CPU sometimes no load more than 50%

i need off ... start from bios sometimes load 100% sometimes don't load... 

i have no other issue . on windows. drivers everything work as well.

i have try also debian 12. have issue audio drivers only...

**Comment by MrChromebox** [comment] 2024-01-19 17:45
not a script issue, dupe of firmware #530

**Closed by MrChromebox** 2024-01-19 17:45 UTC
