### ISSUE TITLE
Could unsupported devices be supported in the future?

### ISSUE THREAD

**Issue by techboyg5** [MrChromebox/scripts#144] opened 2021-01-20 12:58 UTC
Hi there!
My friend just got a Chromebook `BLOOGLET` and it doesn't work on either firmware at the time, according to the [Supported Devices](https://wiki.mrchromebox.tech/Supported_Devices) page.

My question is, could unsupported devices (especially this one) be supported in the future or will they be unsupported forever?

**Comment by MrChromebox** [comment] 2021-01-20 18:13
duplicate of #89, closing

**Closed by MrChromebox** 2021-01-20 18:13 UTC
