### ISSUE TITLE
Support for Gemini Lake anytime soon?

### ISSUE THREAD

**Issue by Kasperfma** [MrChromebox/scripts#132] opened 2020-09-21 20:10 UTC
Title pretty much says it.

I'm having issues with dual booting Linux on a Dell 3100, and i can't find a fix to my problems. Nothing happens when i press CTRL+L on boot. Therefore i looked here for help, but it turns out that it doesn't support my processor.

Is there any solution to this? Is it possible for me to install on this model. If not, when do you expect support for Gemini Lake to be developed?

// Kasper

**Comment by MrChromebox** [comment] 2020-09-21 21:46
duplicate of #89

**Closed by MrChromebox** 2020-09-21 21:46 UTC
