### ISSUE TITLE
Ubuntu server on ASUS Chromebox 3 needs HDMI always connected?

### ISSUE THREAD

**Issue by gmcmicken** [MrChromebox/scripts#206] opened 2022-05-23 21:27 UTC
Turning a Chromebox into a headless server with docker. All went well until I tried to remove HDMI, box became unresponsive but didn't turn off. Rebooting with the HDMI unplugged, ssh server never comes up but I can ping for a moment before it disappears. 

Everything works normally with HDMI connected. Has anyone seen this with ASUS Chromeboxes?

Thanks

**Comment by redpoisonv3** [comment] 2022-05-27 08:58
have you tried a dummy hdmi plug to see if that fixes it?

**Comment by gmcmicken** [comment] 2022-05-27 18:20
> have you tried a dummy hdmi plug to see if that fixes it?

Yes, and it does. Through testing I was able to determine its either HDMI or USB Keyboard required to boot, and more peculiarly if the system is running and both are disconnected, the system is immediately shut down. Not ACPI shutdown either, there are no log messages at all in Linux when these are disconnected, the board is effectively pulled of power the instant the last of either HDMI or USB are unplugged.

I've used a spare Logitech unifying receiver as a workaround.

**Comment by redpoisonv3** [comment] 2022-05-28 02:50
which linux distro are you running ill see if i can replicate the issue on my hp chrome box, the only way i could see a permanent fix would be to create a virtual monitor within the os it self.

**Comment by gmcmicken** [comment] 2022-05-29 00:37
> which linux distro are you running ill see if i can replicate the issue on my hp chrome box, the only way i could see a permanent fix would be to create a virtual monitor within the os it self.

Ubuntu server 20.04

**Comment by MrChromebox** [comment] 2023-02-04 20:14
not a script issue; closing

**Closed by MrChromebox** 2023-02-04 20:14 UTC

**Comment by CyJaySong** [comment] 2024-04-29 00:32
@MrChromebox I have also encountered this issue recently. It seems that I did not have this issue when using version 4.21.1 of Coreboot. I have upgraded to the latest version of Coreboot, but I don't know how to go back to the previous version

**Comment by CyJaySong** [comment] 2024-04-29 00:39
@ferrellsl What is the root cause of this problem? System? Or UEFI?

**Comment by ferrellsl** [comment] 2024-04-29 00:44
> @ferrellsl What is the root cause of this problem? System? Or UEFI?

Not sure of the cause, but a dummy plug should solve the problem and they're less than $1 USD on AliExpress.

**Comment by CyJaySong** [comment] 2024-04-29 00:56
@ferrellsl I want to return the Coreboot V4.21.1 and try again

**Comment by ferrellsl** [comment] 2024-04-29 00:59
> @ferrellsl I want to return the Coreboot V4.21.1 and try again
  The older downloads are here:  https://coreboot.org/downloads.html

**Comment by CyJaySong** [comment] 2024-04-29 01:10
@ferrellsl I have downloaded firmware version 4.21.1, but I don't know how to flash it. This script can only update the latest version estimate

**Comment by ferrellsl** [comment] 2024-04-29 01:12
> @ferrellsl I have downloaded firmware version 4.21.1, but I don't know how to flash it. This script can only update the latest version

Better wait for MrChromebox to respond then.  I'm definitely not the guy who can give you instructions for downgrading.

**Comment by CyJaySong** [comment] 2024-04-29 01:14
@ferrellsl Ok, but, thank you, have a good day😄

**Comment by CyJaySong** [comment] 2024-04-29 01:15
@MrChromebox Hello, thank you for your open-source contribution. Can you guide me on how to downgrade the version?

**Comment by MrChromebox** [comment] 2024-04-29 02:01
@CyJaySong I don't support this at all, but here you go:
https://docs.chrultrabook.com/docs/firmware/manually-flashing.html
