### ISSUE TITLE
Util script says update is available, but no update is available

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [MrChromebox/scripts#424] opened 2024-08-15 01:23 UTC
I have a jinlon which is on the latest MrChromebox firmware. When I run the util script, it says update available. When I update the firmware, it just installs the same firmware that it currently has. Then if I reboot and run the util script again, it says update available.

**Comment by MrChromebox** [comment] 2024-08-15 04:01
duplicate of #377

**Closed by MrChromebox** 2024-08-15 04:01 UTC
